public enum HighlightStatus
{
	NONE,
	MOUSE_HOVER,
	MOUSE_HOVER_CLICKED,
	MOUSE_SELECTED,
	MOUSE_SELECTED_HOVER,
	MOUSE_SELECTED_HOVER_CLICKED,
	MOUSE_ERROR,
	BUILDING_HOVERING,
	BUILDING_HOVERING_ERROR
}
