public enum SequenceActionType
{
	SET_MIDDLE_MESSAGE,
	ENABLE_ARROW_POINTER_3D,
	DISABLE_ARROW_POINTER_3D,
	ENABLE_UI,
	DISABLE_UI,
	SET_PLACE_QUEEN_TRUE,
	SET_PLACE_QUEEN_FALSE,
	UNLOCK_BUILDING_SILENT,
	UNLOCK_BUILDING_POPUP,
	RESEARCH_COST_SET,
	RESEARCH_COST_REVERT,
	RESEARCH_TIME_SET,
	RESEARCH_TIME_REVERT,
	RESEARCH_UNLOCK_SET,
	RESEARCH_UNLOCK_REVERT
}
