public enum TaskRewardType
{
	NONE,
	BUILDING,
	TRAILTYPE,
	UNLOCK_EVERYTHING,
	GIVE_QUEEN_ENERGY,
	TUTORIAL,
	RESET_CAMERA_DISTANCES,
	TUTORIAL_AFTER_TIME,
	GENERAL_UNLOCK,
	QUEEN_MAKE_LARVA,
	REVEAL_BIOME,
	RECIPE,
	GIVE_TECH,
	ADD_REVEAL
}
